### Root
GET http://localhost:5095
### All Games
GET http://localhost:5095/games

### Specific Game
GET http://localhost:5095/games/1

### Add Game
POST http://localhost:5095/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}


### Update Game
PUT http://localhost:5095/games/4
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 39.99,
    "releaseDate": "2011-11-18"
}